### ISSUE TITLE
cannot import name 'PYTEST_COLLECT_MODULE'

### ISSUE THREAD

**Issue by JonathanContreras-bit** [mikeizbicki/sorting#1]
I am trying to run my tests and when I enter
```
python3 -m pytest tests/test_main.py
```
I receive the following error
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/jonathan.contreras2/.local/lib/python3.6/site-packages/pytest/__init__.py", line 3, in <module>
    from . import collect
  File "/home/jonathan.contreras2/.local/lib/python3.6/site-packages/pytest/collect.py", line 8, in <module>
    from _pytest.deprecated import PYTEST_COLLECT_MODULE
ImportError: cannot import name 'PYTEST_COLLECT_MODULE'
```
I have pip installed `requirements.txt` and that seemed to run fine. In that file is a line that reads ```pytest==5.3.1```. I have not experienced difficulties with pytest in the past so I suspect this recent instillation has something to do with it. Would appreciate some help.

**Comment by mikeizbicki** [comment]
resolved in lab
